server:
  port: 8082

spring:
  application:
    name: consumer

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: user-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
#        schema.registry.url: http://localhost:8081
#        specific.avro.reader: true